### ISSUE TITLE
Wrong Datatypes in HMISet

### ISSUE THREAD

**Issue by markusgraube** [p2o-lab/pimad-types#2]
The current implementation of the Picture of a HMISet (https://github.com/p2o-lab/pimad-types/blob/48d028741ad57e75f3e53fa2b2ba25005c3e09e2/src/InformationModel/ModuleTypePackage/MTPHMISUCLib/HMISet-2020-01.ts#L10-L12) is build on DataItems. However, I am quite sure that *Width*, *Height* and the *HierarchyLevel* are just plain attributes in the XML and not reflected in an OPC UA server.

@julorenz Is this correct?

Furthermore, a _Picture_ should also contain a list of _VisualObjects_, _Connections_ and _SemanticGroups_, right?

**Comment by julorenz** [comment]
yes your perfectly right, to be precise each Value of the MTP could be just plain values. Would be the same for static modeled Variables e.g. TagName or Tag Description. This Issue is currently handled by @tuansondinh

**Comment by markusgraube** [comment]
Hi @julorenz , @tuansondinh , can you give some insights about the schedule for solving this issue?

**Comment by tuansondinh** [comment]
Hi @markusgraube, sorry I was busy with controlling services. I plan to solve this issue this week or at the latest in the next week.
